### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/docker-mailcatcher#3]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by vendz** [comment]
@Meldiron @TorstenDittmann can i work on this issue?

**Comment by Meldiron** [comment]
@vendz Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by abhijeet-chatterjee** [comment]
@Meldiron @TorstenDittmann  Can I work on this Issue ?

**Comment by christyjacob4** [comment]
@abhijeet007rocks8 Looks like you have been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by rhythm-sharma** [comment]
Hi @christyjacob4, 

I would like to work on this, could you please assign this to me

**Comment by HeroicHitesh** [comment]
@Meldiron @christyjacob4 Please assign this issue to me.

**Comment by lohanidamodar** [comment]
@rrhythmsharma assigned to you. All the best 🚀

**Comment by rhythm-sharma** [comment]
@lohanidamodar, Thanks I'm on it

**Comment by SoftCreatR** [comment]
@rrhythmsharma Any progress here?

**Comment by rhythm-sharma** [comment]
Sorry bit busy, can you please assign it to someone else

**Comment by SoftCreatR** [comment]
@christyjacob4 I would take this one, then.

**Comment by abhijeet-chatterjee** [comment]
@christyjacob4 can I work on this one.?

**Comment by christyjacob4** [comment]
@SoftCreatR  All the best 👍

**Comment by SoftCreatR** [comment]
Done.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
